fields:
  - name: agent_ephemeral_id
    value: "ac92ed2d-1522-4ff3-a94c-3fe75429e9f1"
  - name: agent_id
    value: "4360059c-b5fe-4184-aec5-197feb898f0a"
  - name: agent_name
    value: "docker-fleet-agent"
  - name: timestamp
    period: -60m
  - name: event_duration
    range:
      min: 0
      max: 100000
  - name: system_memory_total
    range:
      min: 0
      max: 100000000000
  - name: system_memory_used_bytes
    range:
      min: 0
      max: 100000000000
  - name: system_memory_cached
    range:
      min: 0
      max: 100000000000
  - name: system_memory_free
    range:
      min: 0
      max: 1000000000
  - name: system_memory_used_pct
    range:
      min: 0
      max: 1000000
    cardinality: 0.01
  - name: system_memory_actual_used_bytes
    range:
      min: 0
      max: 1000000000
  - name: system_memory_actual_free
    range:
      min: 0
      max: 10000000000
  - name: system_memory_actual_used_pct
    range:
      min: 0
      max: 100
    cardinality: 0.01
  - name: system_memory_swap_total
    range:
      min: 0
      max: 1000000000
  - name: system_memory_swap_used_bytes
    range:
      min: 0
      max: 1000000
  - name: system_memory_swap_free
    range:
      min: 0
      max: 1000000000
  - name: system_memory_swap_used_pct
    range:
      min: 0
      max: 100
    cardinality: 0.01