fields:
  - name: agent_ephemeral_id
    value: 22ed892c-43bd-408a-9121-65e2f5b6a56e
  - name: agent_id
    value: de42127b-4db8-4471-824e-a7b14f478663
  - name: agent_name
    value: "kind-control-plane"
  - name: timestamp
    period: 60m
  - name: event_duration
    range:
      min: 1
      max: 1000000
  - name: status_phase
    enum: ["running", "waiting", "terminated"]
  - name: status_ready
    enum: ["true", "false"]
  - name: restarts
    range:
      min: 1
      max: 100
  - name: reason
    enum: ["ContainerCreating", "CrashLoopBackoff", "ErrImagePull", "ImagePullBackoff", "Completed", "ContainerCannotRun", "Error", "OOMKilled"]
  - name: cpu_limit_cores
    range:
      min: 4
      max: 6
  - name: cpu_request_cores
    range:
      min: 0
      max: 3
  - name: memory_limit_bytes
    range:
      min: 1000000000
      max: 16000000000
  - name: memory_request_bytes
    range:
      min: 500000000
      max: 999000000
  - name: rangeofid
    range:
      min: 0
      max: 10000
  - name: container_name
    enum: ["web", "default-http-backend", "dnsmasq", "csi-driver", "web", "web", "web", "prometheus", "konnectivity-agent", "sidecar", "kubedns", "metrics-server-nanny", "web", "web", "fluentbit", "autoscaler", "gke-metrics-agent", "elastic-agent", "web", "kube-state-metrics", "metrics-server", "fluentbit", "elastic-agent", "web", "prometheus-to-sd-exporter"]
