fields:
  - name: timestamp
    period: -24h
  - name: event_duration
    range:
          min: 1
          max: 10000000
  - name: cloud_region
    enum: ["ap-east-1", "ap-northeast-1", "ap-northeast-2", "ap-northeast-3", "ap-south-1", "ap-southeast-1", "ap-southeast-2", "ca-central-1", "eu-central-1", "eu-north-1", "eu-west-1", "eu-west-2", "eu-west-3", "me-south-1", "sa-east-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"]
  - name: aws_waf_arn
    value: "arn:aws:wafv2:ap-southeast-2:EXAMPLE12345:regional/webacl/STMTest/1EXAMPLE-2ARN-3ARN-4ARN-123456EXAMPLE"
  - name: aws_waf_id
    value: "regional/webacl/STMTest/1EXAMPLE-2ARN-3ARN-4ARN-123456EXAMPLE"
  - name: rule_id
    value: "STMTest_SQLi_XSS"
  - name: rule_ruleset
    enum: ["REGULAR", "GROUP"]
  - name: event_action
    enum: ["ALLOW", "BLOCK"]
  - name: aws_waf_source_name
    value: "ALB"
  - name: aws_waf_source_id
    value: "elb"
  - name: condition_type
    value: "SQL_INJECTION"
  - name: matched_data
    range:
        min: 1
        max: 100
  - name: http_method
    enum: ["GET", "POST", "PUT", "DELETE"]
  - name: bucket_num
    range:
      min: 63461
      max: 63471
  - name: cloud_account_id
    range:
      min: 100000000000
      max: 300000000000
  - name: rangeofid
    range:
      min: 0
      max: 10000
  - name: args
    enum: ["ver=5.0.3", "", "ver=1.1"]
  - name: uri_extension
    enum: [".css", ".png", ".min.css"]
  - name: long_num
    range:
      min: 1000000000
      max: 2000000000
  - name: country_codes
    enum: ["AU", "US", "IN", "GR", "FR", "NZ", "NP"]

    