fields:
  - name: timestamp
    period: 60m
  - name: event_duration
    range:
      min: 0
      max: 100000
  - name: system_diskio_name
    value: "sda2"    
  - name: system_diskio_serial_number
    value: "abcdef123456789"
  - name: system_diskio_read_count
    range:
      min: 0
      max: 100000
  - name: system_diskio_write_count
    range:
      min: 0
      max: 10000000000000
  - name: system_diskio_read_bytes
    range:
      min: 0
      max: 10000000000
  - name: system_diskio_write_bytes
    range:
      min: 0
      max: 10000000000000
  - name: system_diskio_read_time
    range:
      min: 0
      max: 100000
  - name: system_diskio_write_time
    range:
      min: 0
      max: 10000000000000
  - name: system_diskio_io_time
    range:
      min: 0
      max: 10000000
  - name: system_diskio_io_ops
    range:
      min: 0
      max: 1000