fields:
  - name: 'timestamp'
    period: -24h
  - name: agent_ephemeral_id
    value: 14b8ce9f-49d1-4643-8499-23ae7936ea81
  - name: agent_id
    value: 5975706d-e804-462d-b6c0-d70b289d54a7
  - name: agent_name
    value: docker-fleet-agent
  - name: log_level
    enum: ["Note", "Warning", "System", "ERROR"]
  - name: message
    type: text
  - name: thread_id
    range:
      min: 1
      max: 30
