fields:
  - name: agent_ephemeral_id 
    value: "644323b5-5d6a-4dfb-92dd-35ca602db487" 
  - name: agent_id  
    value: "a6147a6e-6626-4a84-9907-f372f6c61eee"
  - name: agent_name 
    value: "agent-ingest-management-clusterscope-674dbb75df-rp8cc"
  - name: deployment_name
    value: keyword
  - name: event_count
    range:
        min: 1
        max: 10000
  - name: event_duration 
    range:
        min: 1
        max: 10000000
  - name: host_id
    value: "b0e83d397c054b8a99a431072fe4617b"
  - name: host_ip
    value: 172.17.0.11
  - name: hostname
    value: "agent-ingest-management-clusterscope-674dbb75df-rp8cc"
  - name: involved_object_api_version
    value: "kibana.k8s.elastic.co/v1"
  - name: involved_object_kind
    value: "Kibana"
  - name: involved_object_name
    value: "monitor"
  - name: involved_object_resource_version
    value: "101842"
  - name: involved_object_uid
    value: "45a19de5-5eef-4090-a2d3-dbceb0a28af8"
  - name: message
    value: "Failed to find referenced backend beats/monitor: Elasticsearch.elasticsearch.k8s.elastic.co \'monitor\' not found"
  - name: metadata_generate_name
    value: "monitor-name"
  - name: metadata_name
    value: "monitor.161bb862545e3099"
  - name: metadata_namespace
    value: "beats"
  - name: metadata_resource_version
    value: "485630"
  - name: metadata_self_link  
    value: "/api/v1/namespaces/beats/events/monitor.161bb862545e3099"
  - name: metadata_uid
    value: "604e39e0-862f-4615-9cec-8cb62299dea3"
  - name: node_hostname
    value: "agent-ingest-management-clusterscope-674dbb75df-rp8cc"
  - name: orchestrator_cluster_name
    value: "kind"
  - name: orchestrator_cluster_url
    value: "kind-control-plane:6443"
  - name: pod_name
    value: "elastic-agent-h2mgj"
  - name: pod_uid
    value: "d06d59c2-929f-4b13-bc7d-c2492200ce07"
  - name: reason
    value: "AssociationError"
  - name: replicaset_name
    value: keyword
  - name: service_address 
    value: "http://kube-state-metrics:8080/metrics" 
  - name: source_component
    value: "kibana-association-controller"
  - name: source_host
    value: "agent-ingest-management-clusterscope-674dbb75df-rp8cc"
  - name: timestamp
    period: 60m
  - name: type
    value: "Warning"