- name: agent_ephemeral_id 
  type: keyword 
- name: agent_id  
  type: keyword
- name: agent_name 
  type: keyword
- name: deployment_name
  type: keyword
- name: event_count
  type: long
- name: event_duration 
  type: long 
- name: event_timestamp_first_occurrence
  type: date
- name: event_timestamp_last_occurrence
  type: date
- name: host_id
  type: keyword
- name: host_ip
  type: ip
- name: hostname
  type: keyword
- name: involved_object_api_version
  type: keyword
- name: involved_object_kind
  type: keyword
- name: involved_object_name
  type: keyword
- name: involved_object_resource_version
  type: keyword
- name: involved_object_uid
  type: keyword
- name: message
  type: text
- name: metadata_generate_name
  type: keyword
- name: metadata_name
  type: keyword
- name: metadata_namespace
  type: keyword
- name: metadata_resource_version
  type: keyword
- name: metadata_self_link  
  type: keyword 
- name: metadata_timestamp_created
  type: date
- name: metadata_uid
  type: keyword
- name: node_hostname
  type: keyword
- name: node_name
  type: keyword
- name: orchestrator_cluster_name
  type: keyword
- name: orchestrator_cluster_url
  type: keyword
- name: pod_ip
  type: ip
- name: pod_name
  type: keyword
- name: pod_uid
  type: keyword
- name: reason
  type: keyword
- name: replicaset_name
  type: keyword
- name: service_address 
  type: keyword 
- name: source_component
  type: keyword
- name: source_host
  type: keyword
- name: statefulset_name
  type: keyword
- name: timestamp
  type: date
- name: type
  type: keyword